name: anna37
channels:
  - conda-forge
  - defaults
dependencies:
  - ipywidgets
  - jupyterlab
  - jupytext
  - python=3.7
  - pip
  - numpy=1.16
  - numba=0.43.1
  - matplotlib
  - scipy
  - scikit-learn

  - pip:
    - -e git+https://github.com/annajxli/pytoolsAL.git#egg=pytoolsAL
    - -e git+https://github.com/cortex-lab/phylib.git#egg=phylib
