name: anna311
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip

  - imageio[ffmpeg]
  - imageio[ffmpeg]
  - ipympl
  - ipywidgets
  - jupyterlab
  - jupytext
  - numpy
  - numba
  - matplotlib
  - opencv-python
  - pandas
  - scipy
  - scikit-learn
  - seaborn
  - tifffile

  - pip:
    - -e git+https://github.com/annajxli/pytoolsAL.git#egg=pytoolsAL
    - -e git+https://github.com/cortex-lab/phylib.git#egg=phylib
