name: anna37
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip

  - ipywidgets=7.6.0
  - jupyterlab=3.2.5
  - jupytext
  - numpy=1.21.4
  - numba=0.43.1
  - matplotlib=3.5.1
  - pandas=1.3.5
  - scipy=1.7.3
  - scikit-learn=1.0.1
  - seaborn 0.11.2

  - pip:
    - -e git+https://github.com/annajxli/pytoolsAL.git#egg=pytoolsAL
    - -e git+https://github.com/cortex-lab/phylib.git#egg=phylib
